version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: workout_db
    ports: 
      - "5432:5432"

      