"""

Revision ID: 4e5f25ef27f7
Revises: a1557a2cf3c7
Create Date: 2024-05-28 17:11:39.492064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5f25ef27f7'
down_revision: Union[str, None] = 'a1557a2cf3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('peso', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atletas', 'peso')
    # ### end Alembic commands ###
